#!/bin/sh

set -x
set -e

mount -a

hostname carino

# launch all the background persistant services
for svc in /etc/services.d/*.svc; do
	${svc} &
done

# guarantee that a shell is always running
while [ 1 ]; do
	/bin/sh -l
	sleep 1
	echo shell killed, restart
done
